FROM ubuntu:26.04
MAINTAINER Andreas Steffen <andreas.steffen@strongswan.org>
ENV VERSION="6.1.0"
ENV SWIDGEN_VERSION="1.1.0"
ENV TZ="Europe/Zurich"
ENV TMPL="/usr/share/strongswan/templates/database/sw-collector"

RUN \
  # set timezone
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
  # install packages
  DEV_PKGS="wget make gcc libssl-dev libsqlite3-dev pkg-config libjson-c-dev" && \
  DEV_PKGS="$DEV_PKGS libcurl4-openssl-dev bzip2" && \
  apt-get -y update && \
  apt-get -y install iproute2 iputils-ping nano sqlite3 libjson-c5 net-tools \
    python3 pipx libcurl4 $DEV_PKGS && \
  \
  # download and build swid_generator
  mkdir /swidGenerator-build && \
  cd /swidGenerator-build && \
  wget https://github.com/strongswan/swidGenerator/archive/refs/tags/v$SWIDGEN_VERSION.tar.gz && \
  tar xf v$SWIDGEN_VERSION.tar.gz && \
  cd swidGenerator-$SWIDGEN_VERSION && \
  pipx install --global --system-site-packages . && \
  cd / && rm -R swidGenerator-build && \
 \
 # download and build strongSwan IKEv2 daemon
  mkdir /strongswan-build && \
  cd /strongswan-build && \
  wget https://download.strongswan.org/strongswan-$VERSION.tar.bz2 && \
  tar xfj strongswan-$VERSION.tar.bz2 && \
  cd strongswan-$VERSION && \
  ./configure --prefix=/usr --sysconfdir=/etc --disable-defaults        \
    --enable-charon --enable-ikev2 --enable-nonce --enable-random       \
    --enable-openssl --enable-pem --enable-x509 --enable-pubkey         \
    --enable-constraints --enable-pki --enable-curl --enable-sqlite     \
    --enable-socket-default --enable-kernel-netlink --enable-updown     \
    --enable-eap-identity --enable-eap-md5 --enable-eap-ttls            \
    --enable-eap-tnc --enable-tnccs-20 --enable-tnc-imc  --enable-vici  \
    --enable-swanctl --enable-resolve --enable-silent-rules             \
    --enable-imc-os --enable-imc-swima --enable-imc-scanner          && \
  make all && make install && \
  cd / && rm -R strongswan-build && \
  ln -s /usr/libexec/ipsec/charon charon && mkdir /etc/pts && \
  cat $TMPL/sw_collector_tables.sql | sqlite3 /etc/pts/collector.db && \
  \
  # clean up
  apt-get -y remove $DEV_PKGS && \
  apt-get -y autoremove && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Expose IKE and NAT-T ports
EXPOSE 500 4500
